spring:
  datasource:
    url : jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#       syso 이기 때문에 운영환경에서는 사용하지 않는다.
#        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL : debug