spring:
#  spring boot 에서는 별도의 설정이 없으면 메모리 디비를 사용한다
  datasource:
    url : jdbc:h2:tcp://localhost/~/jpashop;
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
#       syso 이기 때문에 운영환경에서는 사용하지 않는다.
#        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    open-in-view: false

logging:
  level:
    org.hibernate.SQL : debug
    org.hibernate.type : trace